### ISSUE TITLE
SCP 035 Does not Spawn 

### ISSUE THREAD

**Issue by Parkeymon** [Cyanox62/scp035#20]
The SCP-035 item does not spawn and nobody becomes 035.

**Comment by Specifix5** [comment]
how do u spawn it?

**Comment by Parkeymon** [comment]
You can use `spawn035` but it doesn't spawn naturally, that's why I'm putting it here lol.

**Comment by SoraCent** [comment]
I have the same Problem, Before the 035 got spawned automatically when a spectator is there but now it never spawned since months

**Comment by TheDominikCZ** [comment]
same problem.

**Comment by Parkeymon** [comment]
https://github.com/BuildBoy12/Scp035
