### ISSUE TITLE
Add 035_enable to enable/disable SCP-035, and ideally a command

### ISSUE THREAD

**Issue by PatPeter** [Cyanox62/scp035#3]
It would be convenient for server owners who own more than 1 server to be able to disable plugins from being enabled.

Here's an excerpt from the #plugin-requirements channel in the MultiAdmin Discord:

> - Toggle Option 
> Add a way to disable your plugin. Ideally this should be both a single config bool prefix_disable and a seperate command. However, only a config option is required. A lot of hosts run multiple servers, often these have differences in which plugins they run. By adding the config option, it will become a lot easier to have the plugin run only on some of the servers.

**Comment by Cyanox62** [comment]
I've added this into the latest release.
https://github.com/Cyanox62/scp035/releases/tag/1.5.3

**Comment by PatPeter** [comment]
Ah, sorry about that! I didn't see it in the docs. Thanks for adding it.
